// Generated by gencpp from file idk/Tour.msg
// DO NOT EDIT!


#ifndef IDK_MESSAGE_TOUR_H
#define IDK_MESSAGE_TOUR_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace idk
{
template <class ContainerAllocator>
struct Tour_
{
  typedef Tour_<ContainerAllocator> Type;

  Tour_()
    : nodes()  {
    }
  Tour_(const ContainerAllocator& _alloc)
    : nodes(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _nodes_type;
  _nodes_type nodes;





  typedef boost::shared_ptr< ::idk::Tour_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::idk::Tour_<ContainerAllocator> const> ConstPtr;

}; // struct Tour_

typedef ::idk::Tour_<std::allocator<void> > Tour;

typedef boost::shared_ptr< ::idk::Tour > TourPtr;
typedef boost::shared_ptr< ::idk::Tour const> TourConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::idk::Tour_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::idk::Tour_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::idk::Tour_<ContainerAllocator1> & lhs, const ::idk::Tour_<ContainerAllocator2> & rhs)
{
  return lhs.nodes == rhs.nodes;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::idk::Tour_<ContainerAllocator1> & lhs, const ::idk::Tour_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace idk

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::idk::Tour_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::idk::Tour_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::idk::Tour_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::idk::Tour_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::idk::Tour_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::idk::Tour_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::idk::Tour_<ContainerAllocator> >
{
  static const char* value()
  {
    return "81a3f490b90e9559507f416ae312dc21";
  }

  static const char* value(const ::idk::Tour_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x81a3f490b90e9559ULL;
  static const uint64_t static_value2 = 0x507f416ae312dc21ULL;
};

template<class ContainerAllocator>
struct DataType< ::idk::Tour_<ContainerAllocator> >
{
  static const char* value()
  {
    return "idk/Tour";
  }

  static const char* value(const ::idk::Tour_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::idk::Tour_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[] nodes\n"
;
  }

  static const char* value(const ::idk::Tour_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::idk::Tour_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.nodes);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Tour_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::idk::Tour_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::idk::Tour_<ContainerAllocator>& v)
  {
    s << indent << "nodes[]" << std::endl;
    for (size_t i = 0; i < v.nodes.size(); ++i)
    {
      s << indent << "  nodes[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.nodes[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // IDK_MESSAGE_TOUR_H
